apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    name: tomcat-pod
    context: docker-k8s-lab
spec:
  containers:
    - name: tomcat
      image: smahaboob/app
      ports:
        - containerPort: 8080
      volumeMounts:
      - mountPath: /usr/local/tomcat/logs/
        name: tomcat-volume
  volumes:
    - name: tomcat-volume
      hostPath: 
        path: /home/vagrant/tomcat-storage/
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    name: tomcat-pod
    context: docker-k8s-lab
spec:
  ports:
    - port: 8080
  selector:
    name: tomcat-pod
    context: docker-k8s-lab
  type: NodePort
   

 
