apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: db
    context: docker-k8s-lab
spec:
  containers:
    -
      name: db
      image: smahaboob/db
      ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
    context: docker-k8s-lab
spec:
  ports:
    - port: 3306
  selector:
    name: db
    context: docker-k8s-lab
