apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat-pod
spec:
  replicas: 1
  template:
    metadata:
       labels:
         name: tomcat-pod
         context: docker-k8s-lab
    spec:
       containers:
       - name: tomcat
         image: smahaboob/app
         env:
         - name: "db"
           value: "db"
         ports:
         - name: tomcat-pod
           containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    name: tomcat-pod
    context: docker-k8s-lab
spec:
  ports:
    - port: 8080
  selector:
    name: tomcat-pod
    context: docker-k8s-lab
  type: NodePort
   

 
