apiVersion: v1
kind: Service
metadata:
  name: appversion1
  labels:
    name: appversion1
spec:
  ports:
  - name: http
    nodePort: 31001
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    versions: appversion1
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: dbversion1
  labels:
    name: dbversion1
spec:
  ports:
    - port: 3306
  selector:
    versions: dbversion1
---
apiVersion: v1
kind: Service
metadata:
  name: appversion2
  labels:
    name: appversion2
spec:
  ports:
  - name: http
    nodePort: 31002
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    versions: appversion2
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: dbversion2
  labels:
    name: dbversion2
spec:
  ports:
    - port: 3306
  selector:
    versions: dbversion2
---
apiVersion: v1
kind: Service
metadata:
  name: appversion3
  labels:
    name: appversion3
spec:
  ports:
  - name: http
    nodePort: 31003
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    versions: appversion3
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: dbversion3
  labels:
    name: dbversion3
spec:
  ports:
    - port: 3306
  selector:
    versions: dbversion3

