apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    name: web
spec:
  ports:
    - port: 8080
  selector:
    name: web
  type: NodePort
  
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: web
spec:
  ports:
    - port: 3306
  selector:
    name: web

